export const FundingPoolAbi = [
  { type: "constructor", inputs: [{ name: "admin", type: "address" }], stateMutability: "nonpayable" },
  { type: "receive", stateMutability: "payable" },
  { type: "function", name: "DEFAULT_ADMIN_ROLE", inputs: [], outputs: [{ name: "", type: "bytes32" }], stateMutability: "view" },
  { type: "function", name: "POOL_ADMIN_ROLE", inputs: [], outputs: [{ name: "", type: "bytes32" }], stateMutability: "view" },
  { type: "function", name: "totalDonations", inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "totalYieldDistributed", inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "totalPool", inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "projectBalance", inputs: [{ name: "project", type: "address" }], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "donate", inputs: [{ name: "project", type: "address" }], outputs: [], stateMutability: "payable" },
  { type: "function", name: "allocateFunds", inputs: [{ name: "project", type: "address" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "withdrawProjectFunds", inputs: [{ name: "project", type: "address" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "refundDonors", inputs: [{ name: "project", type: "address" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "claimRefund", inputs: [{ name: "project", type: "address" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "registerProject", inputs: [{ name: "project", type: "address" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "hasRole", inputs: [{ name: "role", type: "bytes32" }, { name: "account", type: "address" }], outputs: [{ name: "", type: "bool" }], stateMutability: "view" },
  { type: "event", name: "Donated", inputs: [{ name: "donor", type: "address", indexed: true }, { name: "project", type: "address", indexed: true }, { name: "amount", type: "uint256", indexed: false }], anonymous: false },
  { type: "event", name: "FundsAllocated", inputs: [{ name: "project", type: "address", indexed: true }, { name: "amount", type: "uint256", indexed: false }], anonymous: false },
  { type: "event", name: "ProjectWithdraw", inputs: [{ name: "project", type: "address", indexed: true }, { name: "researcher", type: "address", indexed: true }, { name: "amount", type: "uint256", indexed: false }], anonymous: false },
  { type: "event", name: "RefundClaimed", inputs: [{ name: "donor", type: "address", indexed: true }, { name: "project", type: "address", indexed: true }, { name: "amount", type: "uint256", indexed: false }], anonymous: false },
] as const;
