export const YieldDistributorAbi = [
  { type: "constructor", inputs: [], stateMutability: "nonpayable" },
  { type: "receive", stateMutability: "payable" },
  { type: "function", name: "DEFAULT_ADMIN_ROLE", inputs: [], outputs: [{ name: "", type: "bytes32" }], stateMutability: "view" },
  { type: "function", name: "YIELD_ADMIN_ROLE", inputs: [], outputs: [{ name: "", type: "bytes32" }], stateMutability: "view" },
  { type: "function", name: "EPOCH_ADMIN_ROLE", inputs: [], outputs: [{ name: "", type: "bytes32" }], stateMutability: "view" },
  { type: "function", name: "WAD", inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "MAX_YIELD_RATE_WAD", inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "MIN_EPOCH_DURATION", inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "rewardIndex", inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "currentEpoch", inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "pendingYield", inputs: [{ name: "user", type: "address" }], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  {
    type: "function",
    name: "yieldSplit",
    inputs: [{ name: "user", type: "address" }],
    outputs: [{ name: "", type: "tuple", components: [{ name: "targetProject", type: "address" }, { name: "donateBps", type: "uint16" }] }],
    stateMutability: "view",
  },
  { type: "function", name: "claimYield", inputs: [], outputs: [{ name: "claimed", type: "uint256" }], stateMutability: "nonpayable" },
  { type: "function", name: "fundYieldPool", inputs: [], outputs: [], stateMutability: "payable" },
  { type: "function", name: "advanceEpoch", inputs: [], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "setYieldRate", inputs: [{ name: "newRateWAD", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "setStakingVault", inputs: [{ name: "vault", type: "address" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "setFundingPool", inputs: [{ name: "fundingPool", type: "address" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "getFundingPool", inputs: [], outputs: [{ name: "", type: "address" }], stateMutability: "view" },
  { type: "function", name: "notifyStake", inputs: [{ name: "user", type: "address" }, { name: "amount", type: "uint256" }, { name: "targetProject", type: "address" }, { name: "donateBps", type: "uint16" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "notifyUnstake", inputs: [{ name: "user", type: "address" }, { name: "amount", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "initialize", inputs: [{ name: "admin", type: "address" }, { name: "initialRateWAD", type: "uint256" }], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "epochInfo", inputs: [{ name: "epoch", type: "uint256" }], outputs: [{ name: "", type: "tuple", components: [{ name: "totalYield", type: "uint256" }, { name: "totalStaked", type: "uint256" }, { name: "yieldRateWAD", type: "uint256" }, { name: "blockNumber", type: "uint256" }, { name: "timestamp", type: "uint256" }] }], stateMutability: "view" },
  { type: "function", name: "hasRole", inputs: [{ name: "role", type: "bytes32" }, { name: "account", type: "address" }], outputs: [{ name: "", type: "bool" }], stateMutability: "view" },
  {
    type: "event",
    name: "YieldClaimed",
    inputs: [
      { name: "user", type: "address", indexed: true },
      { name: "totalClaimed", type: "uint256", indexed: false },
      { name: "toStaker", type: "uint256", indexed: false },
      { name: "toProject", type: "uint256", indexed: false },
      { name: "targetProject", type: "address", indexed: true },
      { name: "epoch", type: "uint256", indexed: false },
      { name: "blockNumber", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  { type: "event", name: "EpochAdvanced", inputs: [{ name: "epoch", type: "uint256", indexed: true }, { name: "totalYield", type: "uint256", indexed: false }, { name: "totalStaked", type: "uint256", indexed: false }, { name: "yieldRateWAD", type: "uint256", indexed: false }, { name: "blockNumber", type: "uint256", indexed: false }], anonymous: false },
  { type: "event", name: "YieldPoolFunded", inputs: [{ name: "funder", type: "address", indexed: true }, { name: "amount", type: "uint256", indexed: false }], anonymous: false },
  { type: "event", name: "FundingPoolSet", inputs: [{ name: "fundingPool", type: "address", indexed: true }], anonymous: false },
  { type: "event", name: "StakingVaultSet", inputs: [{ name: "vault", type: "address", indexed: true }], anonymous: false },
] as const;
